name: Github Release

on: workflow_dispatch

jobs:
  run_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build
        run: |
          rm -rf dist
          poetry build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v0.1.5"
          name: Release ${{ github.ref }}
          draft: false
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}